INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (331, '0 0', 'No rectangle', '0.0', 1);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (332, '0 23', 'No rectangle', '0.0', 1);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (333, '23 0', 'No rectangle', '0.0', 1);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (334, '1 -12', 'Negative numbers not allowed', '-1.0', 1);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (335, '-1 12', 'Negative numbers not allowed', '-1.0', 1);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (336, '4.5 15.5', 'Phải đặt biến số thực', '40.0', 1);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (337, '5 15', '', '40.0', 1);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (338, '0 0', 'No rectangle', '0.0', 2);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (339, '0 23', 'No rectangle', '0.0', 2);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (340, '23 0', 'No rectangle', '0.0', 2);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (341, '1 -12', 'Negative numbers not allowed', '-1.0', 2);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (342, '-1 12', 'Negative numbers not allowed', '-1.0', 2);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (343, '2.5 2.5', 'Phải đặt biến số thực', '6.25', 2);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (344, '2 2', '', '4.0', 2);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (415, '0', 'n can’t be 0', '-1', 3);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (416, '-2', 'n can’t be lower than 1', '-1', 3);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (417, '5', '', '9', 3);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (418, '6', '', '12', 3);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (419, '-2', '', '-1', 4);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (420, '2', 'Is Prime', '1', 4);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (421, '4', 'Is not Prime', '0', 4);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (424, '[64 34 25 12 22 11 90] 22', '', '1', 6);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (425, '[64 34 25 12 22 11 90] 21', '', '0', 6);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (426, '[]', '', '0', 6);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (427, '1 -3 2', 'Có 2 nghiệm phân biệt', '[2.0 1.0]', 8);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (428, '1 2 1', 'Có 1 nghiệm kép', '[-1.0]', 8);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (429, '1 0 -4', 'Có 2 nghiệm phân biệt', '[2.0 -2.0]', 8);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (430, '1 -2 5', 'Không có nghiệm', '[]', 8);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (431, '0 2 -4', 'Ko là pt bậc 2', '[0.0 0.0]', 8);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (432, '-2', 'Không âm', '-1', 7);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (433, '0', '', '0', 7);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (434, '1', '', '1', 7);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (435, '3', '', '2', 7);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (436, '4', '', '4', 7);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (437, '5', '', '7', 7);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (438, '2022 12 1', '', '1', 9);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (439, '2090 12 1', '', '0', 9);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (440, '1000 0 0', 'Ngoại lệ ngày tháng năm', '-1', 9);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (447, '[1 2 3 4 5]', '', '3.0', 13);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (448, '[1 2 2 4]', '', '2.0', 13);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (449, '[]', '', '0.0', 13);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (450, 'LocalDate.of(2000,2,2)', '', '2000', 14);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (451, 'LocalDate.of(2000,2,30)', '', '1900', 14);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (452, '5 2', null, '3', 24);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (453, '2 -3', null, '-1', 24);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (456, '10 5', '', '30240', 17);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (457, '5 10', '', '0', 17);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (458, '-5 2', '', '0', 17);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (459, '-6', '', '0', 17);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (460, '-7', '', '0', 17);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (463, 'Hello, hello', '', '1', 15);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (464, 'Hello helllo', '', '0', 15);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (465, '1', '', '1.0', 12);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (466, '2', '', '2.0', 12);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (467, '64 34 25 12 22 11 90', 'Pass', '[11, 12, 22, 25, 34, 64, 90]', 5);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (471, '1 2', null, '2', 27);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (472, '3 4', '', '12', 27);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (473, 'abcd@gmail.com', '', '1', 11);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (474, 'abcd@*()&.com', '', '0', 11);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (475, 'abcd@gmail.com.vn', '', '1', 11);
INSERT INTO project_thesis_final.bank_test_case_java_core (bank_test_case_id, input_test, note, output_expect, question_java_core_id) VALUES (476, 'abcd@gmail.com@.com', '', '0', 11);
